<h1>Upload</h1>
<p>
    Zurzeit bieten noch keine Uploadfunktion an :(
    <br><br>
    Wenn du deine eigenen Dokumente veröffentlichen willst, sende einfach 
    eine Mail an <a href="mailto:upload@studentbox.ch">upload@studentbox.ch</a>
    <br><br>
    Wir freuen uns über jeden Beitrag den wir erhalten. 
    <br><br>
    <a href="javascript:history.back()"><span class="glyphicon glyphicon-arrow-left"></span> zurück</a>
</p>