<?php
$title = $this->translate('Categories');
$this->headTitle($title);
?>
<h1 class="page-header">
    <?php echo $this->escapeHtml($title); ?>
    <a href="<?php echo $this->url('zfcadmin/category', array('action' => 'add')); ?>" class="btn btn-primary pull-right">
        <?php echo $this->translate('Add new category') ?>
    </a>
</h1>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $category) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($category->name); ?></td>
                <td>
                    <a href="<?php echo $this->url('zfcadmin/category', array('action' => 'edit', 'id' => $category->categoryID)); ?>">
                        <?php echo $this->translate('Edit'); ?>
                    </a> |
                    <a href="<?php echo $this->url('zfcadmin/category', array('action' => 'delete', 'id' => $category->categoryID)); ?>">
                        <?php echo $this->translate('Delete'); ?>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td style="text-align: center;" colspan="3">
                <?php
                echo $this->paginationControl(
                        $this->paginator, 
                        'sliding', 
                        array('partial/paginator.phtml', 'Category'), 
                        array('route' => 'zfcadmin/category')
                );
                ?>
            </td>
        </tr>
    </tfoot>
</table>