<?php echo $this->doctype(); ?>
<html lang="de">
    <head>
        <meta charset="utf-8">

        <?php echo $this->headTitle('Studentbox Admin Interface')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink()->prependStylesheet($this->basePath() . '/css/admin.css')
                ->prependStylesheet('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile('//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js')
                ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')
                ->prependFile('https://oss.maxcdn.com/respond/1.4.2/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile('https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ?>
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Admin Interface</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <?php echo $this->zfcUserIdentity()->getDisplayname(); ?>
                                <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="<?php echo $this->url('zfcuser'); ?>">
                                        <span class="glyphicon glyphicon-user"></span>
                                        Profile
                                    </a>
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <a href="<?php echo $this->url('zfcuser/logout'); ?>">
                                        <span class="glyphicon glyphicon-log-out"></span>
                                        Logout
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-3 col-md-2 sidebar">
                    <?php
                    echo $this->navigation('admin_navigation')
                            ->menu()
                            ->setUlClass('nav nav-sidebar')
                            ->setMaxDepth(0)
                            ->setRenderInvisible(false)
                    ?>
                </div>
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
