<ol class="breadcrumb">
    <li>
        <a href="<?php echo $this->url('download'); ?>">
            <span class="glyphicon glyphicon-home"></span>
        </a>
    </li>
    <li class="active">
        <?php echo $this->escapeHtml($subject->abbreviation); ?>
    </li>
</ol>

<ul class="nav nav-pills nav-stacked">
    <?php
    foreach ($categories as $category) :
        $url = $this->url('download', array('subject' => $subject->subjectID, 'category' => $category->categoryID));
    ?>
    <li>
        <a href="<?php echo $this->escapeHtml($url); ?>" class="list-group-item"> 
            <?php echo $this->escapeHtml($category->name); ?>
        </a>
    </li>
    <?php endforeach; ?>
</ul>