<h1><?php echo sprintf($this->translate('Change Password for %s'), $this->zfcUserDisplayName()); ?></h1>

<?php if ($status === true) : ?>
    <div class="alert alert-success"><?php echo $this->translate('Password changed successfully.'); ?></div>
<?php elseif ($status === false) : ?>
    <div class="alert alert-danger"><?php echo $this->translate('Unable to update your password. Please try again.'); ?></div>
<?php endif; ?>
<?php
$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());
?>

<?php echo $this->form($form, null); ?>