<h1><?php echo $this->translate('Register'); ?></h1>

    <?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}

$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form($form, null); ?>

<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
<?php endif; ?>
<?php echo $this->form()->closeTag() ?>
