<?php
$title = $this->translate('Users');
$this->headTitle($title);

$getters = array();
foreach ($this->userlistElements as $element) {
    $parts = explode('_', $element);
    array_walk($parts, function (&$val) {
        $val = ucfirst($val);
    });
    $getters[$element] = 'get' . implode('', $parts);
}
?>

<h1 class="page-header">
    <?php echo $this->escapeHtml($title); ?>
    <a href="<?php echo $this->url('zfcadmin/zfcuseradmin/create'); ?>" class="btn btn-primary pull-right">
        <?php echo $this->translate('Add new user') ?>
    </a>
</h1>

<table class="table">
    <thead>
        <tr>
            <?php foreach ($this->userlistElements as $name => $element): ?>
                <th><?php echo $this->escapeHtml($name ? : $element); ?></th>
            <?php endforeach; ?>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->users as $user): ?>
            <tr>
                <?php foreach ($this->userlistElements as $element): ?>
                    <td>
                        <?php $parts = explode('_', $element); ?>
                        <?php echo call_user_func(array($user, $getters[$element])); ?>
                    </td>
                <?php endforeach; ?>
                <td>
                    <a href="<?php echo $this->url('zfcadmin/zfcuseradmin/edit', array('userId' => $user->getId())); ?>">
                        <?php echo $this->translate('Edit') ?>
                    </a>
                    |
                    <a href="<?php echo $this->url('zfcadmin/zfcuseradmin/remove', array('userId' => $user->getId())); ?>"
                       onclick="return confirm('<?php echo $this->translate('Really delete user?') ?>')">
                        <?php echo $this->translate('Delete') ?>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
    <tfoot>
        <tr>
            <td style="text-align: center;" colspan="<?php echo count($this->userlistElements) + 1; ?>">
                <?php 
                echo $this->paginationControl(
                        $this->users, 
                        'Sliding', 
                        'zfc-user-admin/user-admin/pagination_userlist.phtml'
                ); 
                ?>
            </td>
        </tr>
    </tfoot>
</table>