<?php if ($this->pageCount > 1): ?>
    <div>
        <ul class="pagination">
            <!-- First page link -->
            <?php if (isset($this->first)): ?>
                <li>
                    <a href="<?php echo $this->url('zfcadmin/zfcuseradmin/list', array('p' => $this->first)); ?>">
                        <<
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <<
                    </a>
                </li>
            <?php endif; ?>
                
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url('zfcadmin/zfcuseradmin/list', array('p' => $this->previous)); ?>">
                        <
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        <
                    </a>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url('zfcadmin/zfcuseradmin/list', array('p' => $page)); ?>">
                            <?php echo $page; ?>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="active">
                        <a href="#"><?php echo $page; ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url('zfcadmin/zfcuseradmin/list', array('p' => $this->next)); ?>">
                        >
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        >
                    </a>
                </li>
            <?php endif; ?>

            <!-- Last page link -->
            <?php if (isset($this->last)): ?>
                <li>
                    <a href="<?php echo $this->url('zfcadmin/zfcuseradmin/list', array('p' => $this->last)); ?>">
                        >>
                    </a>
                </li>
            <?php else: ?>
                <li class="disabled">
                    <a href="#">
                        >>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>