<?php echo $this->doctype(); ?>

<html lang="de">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('StudentBox')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php
        echo $this->headLink(array(
                    'rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/img/favicon.ico'
                ))
                ->prependStylesheet($this->basePath() . '/css/custom.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->prependStylesheet('http://fonts.googleapis.com/css?family=Roboto:700')
        ?>
        <?php
        echo $this->headScript()->appendFile($this->basePath() . '/js/bootstrap.min.js')
                ->appendFile($this->basePath() . '/js/chosen.jquery.min.js')
                ->prependFile($this->basePath() . '/js/jquery-1.11.0.min.js')
        ?>
        <script>
            (function(i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r;
                i[r] = i[r] || function() {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                        m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-51335487-1', 'studentbox.ch');
            ga('send', 'pageview');
        </script>
    </head>
    <body>
        <div class="container" id="wrap">
            <div class="row" id="main-row">
                <div class="col-md-12">
                    <a href="/" id="title-link"><h1 id="title">StudentBox</h1></a>
                </div>
                <div class="col-md-6 col-md-offset-3 col-xs-12 col-xs-offset-0">
                    <?php echo $this->content; ?>
                </div>
            </div>
            <!--Für Footer-->
            <div id="push"></div>
        </div>

        <footer>
            <div class="container">
                <p class="text-muted pull-right">
                    <a href="https://github.com/studentbox/website" target="_blank">
                        <img style="height: 16px;" src="<?php echo $this->basePath() . '/img/GitHub-Mark-32px.png' ?>" alt="See us on Github">
                    </a>

                    <?php if (!$this->zfcUserIdentity()): ?>
                        | <a href="<?= $this->url('zfcuser') ?>">Login</a>
                    <?php endif; ?>
                </p>
            </div>
        </footer>

        <?php echo $this->inlineScript() ?>
    </body>
</html>