<?php
$title = $this->translate('Delete subject');
$this->headTitle($title);
?>
<h1 class="page-header"><?php echo $this->escapeHtml($title); ?></h1>

<p>
    <?php echo sprintf($this->translate('Are you sure that you want to delete %s?'), $this->escapeHtml($subject->name)); ?>
</p>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('zfcadmin/subject', array('action' => 'delete', 'id' => $this->id)));
$form->get('id')->setAttribute('value', $this->id);
$messages = $form->get('id')->getMessages();
?>

<?php if ($messages) : ?>
    <div class="alert alert-warning">
        <p>
            <?php
            foreach ($messages as $message) {
                echo $message . "\n";
            }
            ?>
        </p>
        <p>
            <a href="<?php echo $this->url('download', array('subject' => $subject->abbreviation)); ?>">
                <?php echo $this->translate('go to') . ' ' . $subject->name; ?>
            </a>
        </p>
    </div>
<?php endif; ?>

<?php
echo $this->form()->openTag($form);
echo $this->formElement($form->get('id'));

echo $this->formButton($form->get('yes'));
echo ' ';
echo $this->formButton($form->get('no'));
echo $this->form()->closeTag();
?>
